name: time capsule

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image push to aliyun
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
        password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}
        tags: ${{ github.sha }}
        repository: reddwarf-pro/time-capsule
        path: '.'

    #- name: deploy to cluster
    #  uses: steebchen/kubectl@v2.0.0
    #  with: 
    #    config: ${{ secrets.KUBE_CONFIG_DATA }}
    #    command: set image --record deployment/time-capsule-service time-capsule-service=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/#reddwarf-pro/time-capsule:${{ github.sha }} -n reddwarf-pro
    
    - name: retry action
      uses: Wandalen/wretry.action@v1.0.11
      with:
        action: steebchen/kubectl@v2.0.0
        with: |
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/time-capsule-service time-capsule-service=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/time-capsule:${{ github.sha }} -n reddwarf-pro
        attempt_limit: 3
        attempt_delay: 2000

    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0
        command: rollout status deployment/time-capsule-service -n reddwarf-pro
